#pragma once
#include <cstdint>


enum class LogVerbose {
	Info,
	Warn,
	Err,
	Fatal
};

enum class KaibzHudFlag : uint64_t {
	ShowNumbers = 0x1,
	ShowExtraLives = 0x2,
	ShowBloodPunch = 0x4,
	ShowRadsuitOrOxygen = 0x8,
	ShowBasics = 0x10, //! health, armor and ammo
	ShowHammerOrCrucible = 0x20,
	ShowFlameBelch = 0x40,
	ShowFuel = 0x80,
	ShowFragOrEquipment = 0x100,
	ShowIce = 0x200,
	HideHudInAds = 0x400, //! leaving some available flags for later may be
	Unused2 = 0x800,
	Unused3 = 0x1000,
	Unused4 = 0x2000,
	Unused5 = 0x4000,
	FlashHudForFragCount = 0x8000,
	FlashHudForIceCount = 0x10000,
	FlashHudForBloodPunchCount = 0x20000,
	FlashHudForHammerCount = 0x40000,
	Unused10 = 0x80000,
	Unused11 = 0x100000,
	Unused12 = 0x200000,
	Unused13 = 0x400000,
	Unused14 = 0x800000,
	Unused15 = 0x1000000,
	Unused16 = 0x2000000,
	Unused17 = 0x4000000,
	Unused18 = 0x8000000,
	Unused19 = 0x10000000,
	Unused20 = 0x20000000,
	Unused21 = 0x40000000,
	Unused22 = 0x80000000,
	Unused23 = 0x100000000,
	Unused24 = 0x200000000,
	Unused25 = 0x400000000,
	Unused26 = 0x800000000,
	Unused27 = 0x1000000000,
	Unused28 = 0x2000000000,
	Unused29 = 0x4000000000,
	Unused30 = 0x8000000000,
	Unused31 = 0x10000000000,
	Unused32 = 0x20000000000,
	Unused33 = 0x40000000000,
	Unused34 = 0x80000000000,
	Unused35 = 0x100000000000,
	Unused36 = 0x200000000000,
	Unused37 = 0x400000000000,
	Unused38 = 0x800000000000,
	Unused39 = 0x1000000000000,
	Unused40 = 0x2000000000000,
	Unused41 = 0x4000000000000,
	Unused42 = 0x8000000000000,
	Unused43 = 0x10000000000000,
	Unused44 = 0x20000000000000,
	Unused45 = 0x40000000000000,
	Unused46 = 0x80000000000000,
	Unused47 = 0x100000000000000,
	Unused48 = 0x200000000000000,
	Unused49 = 0x400000000000000,
	Unused50 = 0x800000000000000,
	Unused51 = 0x1000000000000000,
	Unused52 = 0x2000000000000000,
	Unused53 = 0x4000000000000000,
	Unused54 = 0x8000000000000000
};


enum class KaibzHudColor_t {
	disabledColor,
	cautionColor,
	warningColor,
	criticalColor,
	extraLivesColor,
	bloodPunch1Color,
	bloodPunch2Color,
	bloodPunchDesperateColor, //! desperate punch
	healthMaxColor,
	healthColor, //! the low and critical will be from warningColor and criticalColor
	armorMaxColor,
	armorColor,
	radsuitColor, //! the low and critical will be from warningColor and criticalColor
	oxygenColor,
	ammoColor,
	hammerCrucibleColor,
	flameBelchColor,
	fuel1Color,
	fuel2Color,
	fuel3Color,
	frag1Color,
	frag2Color,
	iceColor,
	iceColorCoolDown
};

enum class HealthState_K {
	maxed,
	normal,
	low,
	critical
};

enum class ArmorState {
	maxed,
	normal
};


enum class AmmoState_K {
	normal,
	low, //! or critical instead?
};

//! for rad and oxygen
enum class MeterState_K {
	normal,
	low,
	critical
};


enum class KaibzHudData_barStatus {
	notOwned,
	normal,
	low,
	max
};


enum hudSpriteId_t : __int32 {
	HUD_SPRITE_ID_UNKNOWN,
	HUD_SPRITE_ID_FLAMEBELCH,
	HUD_SPRITE_ID_FUEL,
	HUD_SPRITE_ID_FRAG,
	HUD_SPRITE_ID_ICE,
	HUD_SPRITE_ID_CRUCIBLE,
	HUD_SPRITE_ID_HAMMER,
	HUD_SPRITE_ID_BLOODPUNCH,
	HUD_SPRITE_ID_DASH, // hopefully we won't have to use that
	HUD_SPRITE_ID_AMMOS_UNKNOWN,
	HUD_SPRITE_ID_AMMOS_SHELL, // our custom implementation
	HUD_SPRITE_ID_AMMOS_BULLET, // our custom implementation
	HUD_SPRITE_ID_AMMOS_ROCKET, // our custom implementation
	HUD_SPRITE_ID_AMMOS_CELL, // our custom implementation
	HUD_SPRITE_ID_MAX,
};


//! not part of idLib just refs we can use to id game items. 
//? this doesn't list all the items a player can have only the one we're interested in. order is important for weap slot compare.
enum class ItemRef {
	UNKNOWN = 0,
	WEAPON_PLAYER_SHOTGUN = 1,
	WEAPON_PLAYER_HEAVY_CANNON = 2,
	WEAPON_PLAYER_PLASMA_RIFLE = 3,
	WEAPON_PLAYER_ROCKET_LAUNCHER = 4,
	WEAPON_PLAYER_DOUBLE_BARREL = 5,
	WEAPON_PLAYER_GAUSS_RIFLE = 6,
	WEAPON_PLAYER_CHAINGUN = 7,
	WEAPON_PLAYER_BFG = 8,
	WEAPON_PLAYER_UNMAYKR = 9,
	WEAPON_PLAYER_CRUCIBLE = 10,
	WEAPON_PLAYER_HAMMER = 11,
	ABILITIES_BLOOD_PUNCH,
	ABILITIES_ENVIRONMENTSUIT,
	ABILITIES_GRAPPLEGLOVES,
	ABILITY_DASH,
	ACTORMODIFIER_SP_DEMON_REVENANT,
	AMMO_PLAYER_DOOMBLADE,
	AMMO_SHAREDAMMOPOOL_BFG,
	AMMO_SHAREDAMMOPOOL_BULLETS,
	AMMO_SHAREDAMMOPOOL_CELLS,
	AMMO_SHAREDAMMOPOOL_CRUCIBLE,
	AMMO_SHAREDAMMOPOOL_HAMMER,
	AMMO_SHAREDAMMOPOOL_FIST,
	AMMO_SHAREDAMMOPOOL_FUEL,
	AMMO_SHAREDAMMOPOOL_ROCKETS,
	AMMO_SHAREDAMMOPOOL_SHELLS,
	CHARGE_ATTACK_BASE,
	EQUIPMENT_FLAME_BELCH,
	EQUIPMENTLAUNCHER_EQUIPMENTLAUNCHERLEFT,
	EXTRA_LIFE,
	JUMPBOOTS_BASE,
	THROWABLE_PLAYER_FRAG_GRENADE,
	THROWABLE_PLAYER_ICE_BOMB,
	WEAPON_PLAYER_CHAINSAW,
	WEAPON_PLAYER_DOOMBLADE,
	WEAPON_PLAYER_EQUIPMENT_FLAME_BELCH,
	WEAPON_PLAYER_FISTS,
	WEAPON_PLAYER_FISTS_BERSERK,
	WEAPON_PLAYER_FISTS_DOOM5MELEE,
	WEAPON_PLAYER_FISTS_SWIM,
	WEAPON_PLAYER_POINTING_ARM
};


enum class weaponSlot_t {
	UNDEFINED = -1,
	SHOTGUN = 1,
	HAR = 2,
	PLASMA = 3,
	ROCKET = 4,
	SSG = 5,
	BALLISTA = 6,
	CHAINGUN = 7,
	BFG_UNMAYKR = 8,
	WEAPON_9 = 9,
	CRUCIBLE_HAMMER = 10,
	MAX_WEAPON_SLOT
};


enum gameSpeed_K {
	defaultSpeed,
	X2_Speed,
	maxSpeed
};


enum class antialiasingLevel {
	UNKNOWN = -1,
	DISABLED = 0,
	TEMPORAL_SSA_X32 = 1,
	NVIDIA_DLSS = 2
};



//? this could actually change in a game update, might need to be careful....
//! used for ex in idSWFSpriteInstance.h
enum swfNamedColors_t : int {

	SWF_NAMED_COLOR_INVALID = -1,
	SWF_NAMED_COLOR_HUD_BASE = 0,
	SWF_NAMED_COLOR_HUD_SHADOW = 1, //! changes with ui profile
	SWF_NAMED_COLOR_HUD_TEXT = 2,  // this might be the color of the hud arrow but it will change if user has set a different color profile...
	SWF_NAMED_COLOR_HUD_HEADER = 3,
	SWF_NAMED_COLOR_DASH_BASE = 4,
	SWF_NAMED_COLOR_DASH_GLOW = 5,
	SWF_NAMED_COLOR_NOTIFICATION_GHOST = 6,
	SWF_NAMED_COLOR_UI_HEALTH = 7,
	SWF_NAMED_COLOR_UI_HEALTH_GRADIENT = 8,
	SWF_NAMED_COLOR_UI_HEALTH_LOW = 9,
	SWF_NAMED_COLOR_UI_HEALTH_REALLY_LOW = 10,
	SWF_NAMED_COLOR_UI_HEALTH_DEMON = 11,
	SWF_NAMED_COLOR_UI_ARMOR = 12,
	SWF_NAMED_COLOR_UI_ARMOR_GRADIENT = 13,
	SWF_NAMED_COLOR_UI_RADIATION = 14,
	SWF_NAMED_COLOR_UI_RADIATION_GRADIENT = 15,
	SWF_NAMED_COLOR_UI_OXYGEN = 16,
	SWF_NAMED_COLOR_UI_OXYGEN_GRADIENT = 17,
	SWF_NAMED_COLOR_UI_WARNING = 18,
	SWF_NAMED_COLOR_UI_CAUTION = 19,
	SWF_NAMED_COLOR_UI_SUCCESS = 20,
	SWF_NAMED_COLOR_UI_FAILURE = 21,
	SWF_NAMED_COLOR_UI_PROGRESS_BAR_FILL = 22,
	SWF_NAMED_COLOR_UI_PROGRESS_COMPLETE = 23,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_BACKGROUND = 24,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_BACKGROUND_LOW = 25,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_BACKGROUND_REALLY_LOW = 26,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_BACKGROUND_DEAD = 27,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_BACKGROUND_GLOW = 28,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_BACKGROUND_GLOW_LOW = 29,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_BACKGROUND_GLOW_REALLY_LOW = 30,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_PIP_GREEN = 31,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_PIP_GREEN_GRADIENT = 32,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_PIP_ORANGE = 33, //!  will not be orange if in demon mode so this color will change depending on ui profile
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_PIP_ORANGE_GRADIENT = 34,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_PIP_BLUE = 35,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_PIP_BLUE_GRADIENT = 36,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_PIP_LOW = 37,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_PIP_LOW_GRADIENT = 38,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_PIP_DEAD = 39,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_ICON = 40,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_ICON_GRADIENT = 41,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_ICON_LOW = 42,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_ICON_GRADIENT_LOW = 43,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_ICON_REALLY_LOW = 44,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_ICON_GRADIENT_REALLY_LOW = 45,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_ICON_DEAD = 46,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_ICON_GRADIENT_DEAD = 47,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_GLOW_BITS = 48,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_GLOW_BITS_LOW = 49,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_TEXT = 50,
	SWF_NAMED_COLOR_UI_DEMON_HEALTH_TEXT_LOW = 51,
	SWF_NAMED_COLOR_WORLD_UNLOCKED = 52,
	SWF_NAMED_COLOR_WORLD_LOCKED = 53,
	SWF_NAMED_COLOR_SLAYER_GREEN = 54, //! changes with ui profile
	SWF_NAMED_COLOR_DEMON_RED = 55,
	SWF_NAMED_COLOR_DEMON_YELLOW = 56, //! keeps yellow color in any profile
	SWF_NAMED_COLOR_WHITE = 57, //! keeps yellow color in any profile
	SWF_NAMED_COLOR_WEAPON_CHAINSAW = 58, //! weapons colors change with ui profile
	SWF_NAMED_COLOR_WEAPON_SHOTGUN = 59,
	SWF_NAMED_COLOR_WEAPON_DOUBLE_BARREL = 60,
	SWF_NAMED_COLOR_WEAPON_ASSUALT_RIFLE = 61,
	SWF_NAMED_COLOR_WEAPON_CHAINGUN = 62,
	SWF_NAMED_COLOR_WEAPON_PLASMA_RIFLE = 63,
	SWF_NAMED_COLOR_WEAPON_BALLISTA = 64,
	SWF_NAMED_COLOR_WEAPON_ROCKET_LAUNCHER = 65,
	SWF_NAMED_COLOR_WEAPON_BFG = 66,
	SWF_NAMED_COLOR_WEAPON_UNMAYKR = 67,
	SWF_NAMED_COLOR_WEAPON_CRUCIBLE = 68,
	SWF_NAMED_COLOR_WEAPON_HAMMER = 69,
	SWF_NAMED_COLOR_WEAPON_NO_AMMO = 70,
	SWF_NAMED_COLOR_WEAPON_DISABLED = 71,
	SWF_NAMED_COLOR_WEAPON_SHOTGUN_FULL = 72,
	SWF_NAMED_COLOR_WEAPON_DOUBLE_BARREL_FULL = 73,
	SWF_NAMED_COLOR_WEAPON_ASSUALT_RIFLE_FULL = 74,
	SWF_NAMED_COLOR_WEAPON_CHAINGUN_FULL = 75,
	SWF_NAMED_COLOR_WEAPON_PLASMA_RIFLE_FULL = 76,
	SWF_NAMED_COLOR_WEAPON_BALLISTA_FULL = 77,
	SWF_NAMED_COLOR_WEAPON_ROCKET_LAUNCHER_FULL = 78,
	SWF_NAMED_COLOR_WEAPON_BFG_FULL = 79,
	SWF_NAMED_COLOR_WEAPON_UNMAYKR_FULL = 80,
	SWF_NAMED_COLOR_WEAPON_HAMMER_FULL = 81,
	SWF_NAMED_COLOR_RETICLE_BASE = 82,
	SWF_NAMED_COLOR_RETICLE_GLOW = 83,
	SWF_NAMED_COLOR_RETICLE_COOLDOWN_BASE = 84,
	SWF_NAMED_COLOR_RETICLE_COOLDOWN_GLOW = 85,
	SWF_NAMED_COLOR_RETICLE_WARNING_BASE = 86, // nice orange in all huds but reddish in demon hud
	SWF_NAMED_COLOR_RETICLE_WARNING_GLOW = 87,
	SWF_NAMED_COLOR_RETICLE_ALT_STROKE = 88,
	SWF_NAMED_COLOR_RETICLE_ALT_BASE = 89,
	SWF_NAMED_COLOR_RETICLE_ALT_GLOW = 90,
	SWF_NAMED_COLOR_RETICLE_ALT2_STROKE = 91,
	SWF_NAMED_COLOR_RETICLE_ALT2_BASE = 92,
	SWF_NAMED_COLOR_RETICLE_ALT2_GLOW = 93,
	SWF_NAMED_COLOR_KEYCARD_BLUE = 94,
	SWF_NAMED_COLOR_KEYCARD_RED = 95,
	SWF_NAMED_COLOR_KEYCARD_YELLOW = 96,
	SWF_NAMED_COLOR_KEYCARD_SLAYER = 97,
	SWF_NAMED_COLOR_MENU_BACK_BASE = 98, // not linked to equipment arrow color
	SWF_NAMED_COLOR_MENU_BACK_STROKE = 99,
	SWF_NAMED_COLOR_MENU_SELECTION_BASE = 100,
	SWF_NAMED_COLOR_MENU_SELECTION_STROKE = 101,
	SWF_NAMED_COLOR_MENU_BACK_PRESS = 102,
	SWF_NAMED_COLOR_MENU_HEADER_TEXT = 103,
	SWF_NAMED_COLOR_COLLECTED_ITEM = 104,
	SWF_NAMED_COLOR_CORRUPTION_HEX_CLEARED = 105,
	SWF_NAMED_COLOR_CORRUPTION_HEX_GLOW_CLEARED = 106,
	SWF_NAMED_COLOR_CORRUPTION_HEX_CORRUPT = 107,
	SWF_NAMED_COLOR_CORRUPTION_HEX_GLOW_CORRUPT = 108,
	SWF_NAMED_COLOR_CORRUPTION_CONTAINER_CLEARED = 109,
	SWF_NAMED_COLOR_CORRUPTION_CONTAINER_CORRUPT = 110,
	SWF_NAMED_COLOR_CORRUPTION_CLEARED = 111,
	SWF_NAMED_COLOR_CORRUPTION_CLEARED_GLOW = 112,
	SWF_NAMED_COLOR_CORRUPTION_PARTIAL_CLEARED = 113,
	SWF_NAMED_COLOR_CORRUPTION_PARTIAL_CLEARED_GLOW = 114,
	SWF_NAMED_COLOR_CORRUPTION_COMBAT = 115,
	SWF_NAMED_COLOR_CORRUPTION_COMBAT_GLOW = 116,
	SWF_NAMED_COLOR_CORRUPTION_SLAYER_GATE = 117,
	SWF_NAMED_COLOR_CORRUPTION_SLAYER_GATE_GLOW = 118,
	SWF_NAMED_COLOR_CORRUPTION_SECRET = 119,
	SWF_NAMED_COLOR_CORRUPTION_SECRET_GLOW = 120,
	SWF_NAMED_COLOR_CORRUPTION_BOSS = 121,
	SWF_NAMED_COLOR_CORRUPTION_BOSS_GLOW = 122,
	SWF_NAMED_COLOR_CORRUPTION_BASE = 123,
	SWF_NAMED_COLOR_CORRUPTION_OVERLAY = 124,
	SWF_NAMED_COLOR_CORRUPTION_ESCALATION = 125,
	SWF_NAMED_COLOR_CORRUPTION_ESCALATION_GLOW = 126,
	SWF_NAMED_COLOR_EXTRA_LIFE_ICON = 127,
	SWF_NAMED_COLOR_EXTRA_LIFE_ICON_GLOW = 128,
	SWF_NAMED_COLOR_EXTRA_LIFE_TIMER = 129,
	SWF_NAMED_COLOR_EXTRA_LIFE_TIMER_GLOW = 130,
	SWF_NAMED_COLOR_ARGENT_CELL = 131,
	SWF_NAMED_COLOR_WEAPON_POINT = 132,
	SWF_NAMED_COLOR_PRAETOR_POINT = 133,
	SWF_NAMED_COLOR_SENTINEL_BATTERY = 134,
	SWF_NAMED_COLOR_DEMON_HUD_BACKER = 135,
	SWF_NAMED_COLOR_DEMON_HUD_ABILITIES_SELECTION_GLOW = 136,
	SWF_NAMED_COLOR_DEMON_HUD_ABILITIES_SELECTION_STROKE = 137,
	SWF_NAMED_COLOR_DEMON_HUD_ABILITY_FRAME = 138,
	SWF_NAMED_COLOR_DEMON_HUD_ABILITY_FRAME_GLOW_UNSELECTED = 139,
	SWF_NAMED_COLOR_DEMON_HUD_ABILITY_FRAME_GLOW_SELECTED = 140,
	SWF_NAMED_COLOR_DEMON_HUD_TEAL_BASE = 141,  //! DEMON_HUD_ will change alpha a bit in demon ui
	SWF_NAMED_COLOR_DEMON_HUD_TEAL_GRADIENT = 142,
	SWF_NAMED_COLOR_DEMON_HUD_TEAL_OVERLAY = 143,
	SWF_NAMED_COLOR_DEMON_HUD_TEAL_ICON = 144,
	SWF_NAMED_COLOR_DEMON_HUD_YELLOW_BASE = 145,
	SWF_NAMED_COLOR_DEMON_HUD_YELLOW_GRADIENT = 146,
	SWF_NAMED_COLOR_DEMON_HUD_YELLOW_OVERLAY = 147,
	SWF_NAMED_COLOR_DEMON_HUD_YELLOW_ICON = 148,
	SWF_NAMED_COLOR_DEMON_HUD_ORANGE_BASE = 149,
	SWF_NAMED_COLOR_DEMON_HUD_ORANGE_GRADIENT = 150,
	SWF_NAMED_COLOR_DEMON_HUD_ORANGE_OVERLAY = 151,
	SWF_NAMED_COLOR_DEMON_HUD_ORANGE_ICON = 152,
	SWF_NAMED_COLOR_DEMON_HUD_BLUE_BASE = 153,
	SWF_NAMED_COLOR_DEMON_HUD_BLUE_GRADIENT = 154,
	SWF_NAMED_COLOR_DEMON_HUD_BLUE_OVERLAY = 155,
	SWF_NAMED_COLOR_DEMON_HUD_BLUE_ICON = 156,
	SWF_NAMED_COLOR_DEMON_HUD_PURPLE_BASE = 157,
	SWF_NAMED_COLOR_DEMON_HUD_PURPLE_GRADIENT = 158,
	SWF_NAMED_COLOR_DEMON_HUD_PURPLE_OVERLAY = 159,
	SWF_NAMED_COLOR_DEMON_HUD_PURPLE_ICON = 160,
	SWF_NAMED_COLOR_DEMON_HUD_RED_BASE = 161,
	SWF_NAMED_COLOR_DEMON_HUD_RED_GRADIENT = 162,
	SWF_NAMED_COLOR_DEMON_HUD_RED_OVERLAY = 163,
	SWF_NAMED_COLOR_DEMON_HUD_RED_ICON = 164,
	SWF_NAMED_COLOR_DEMON_HUD_GREEN_BASE = 165,
	SWF_NAMED_COLOR_DEMON_HUD_GREEN_GRADIENT = 166,
	SWF_NAMED_COLOR_DEMON_HUD_GREEN_OVERLAY = 167,
	SWF_NAMED_COLOR_DEMON_HUD_GREEN_ICON = 168,
	SWF_NAMED_COLOR_DEMON_HUD_ICON_COOLDOWN = 169,
	SWF_NAMED_COLOR_DEMON_HUD_BASE_COOLDOWN = 170,
	SWF_NAMED_COLOR_DEMON_HUD_GRADIENT_COOLDOWN = 171,
	SWF_NAMED_COLOR_DEMON_HUD_OVERLAY_COOLDOWN = 172,
	SWF_NAMED_COLOR_DEMON_HUD_ABILITY_COOLDOWN_COVER = 173,
	SWF_NAMED_COLOR_DEMON_HUD_WHEEL_STROKE = 174,
	SWF_NAMED_COLOR_DEMON_HUD_WHEEL_BASE = 175,
	SWF_NAMED_COLOR_DEMON_HUD_WHEEL_GLOW = 176,
	SWF_NAMED_COLOR_DEMON_HUD_NOTIFICATION_BASE = 177,
	SWF_NAMED_COLOR_DEMON_HUD_NOTIFICATION_ICON = 178,
	SWF_NAMED_COLOR_DEMON_HUD_NOTIFICATION_STROKE = 179,
	SWF_NAMED_COLOR_DEMON_HUD_NOTIFICATION_HEADER = 180,
	SWF_NAMED_COLOR_DEMON_HUD_NOTIFICATION_TEXT = 181,
	SWF_NAMED_COLOR_DEMON_HUD_NOTIFICATION_GLOW = 182,
	SWF_NAMED_COLOR_DEMON_HUD_DEMON_PLAYER_FRAME = 183,
	SWF_NAMED_COLOR_DEMON_HUD_SLAYER_PLAYER_FRAME = 184,
	SWF_NAMED_COLOR_DEMON_HUD_DEMON_PLAYER_FRAME_BACKGLOW = 185,
	SWF_NAMED_COLOR_DEMON_HUD_SLAYER_PLAYER_FRAME_BACKGLOW = 186,
	SWF_NAMED_COLOR_DEMON_HUD_HEADER_TEXT = 187,
	SWF_NAMED_COLOR_DEMON_HUD_HEADER_TEXT_NUMBERS = 188,
	SWF_NAMED_COLOR_DEMON_HUD_SUMMARY_FRAME = 189,
	SWF_NAMED_COLOR_DEMON_HUD_SUMMARY_BACKING = 190,
	SWF_NAMED_COLOR_HUD_STATUS_BUFF_BACKGLOW = 191,
	SWF_NAMED_COLOR_HUD_STATUS_BUFF_BACKER = 192,
	SWF_NAMED_COLOR_MENU_SEASON_BASE = 193,
	SWF_NAMED_COLOR_COSMETIC_RARITY_DEFAULT = 194,
	SWF_NAMED_COLOR_COSMETIC_RARITY_TIER_1 = 195,
	SWF_NAMED_COLOR_COSMETIC_RARITY_TIER_2 = 196,
	SWF_NAMED_COLOR_COSMETIC_RARITY_TIER_3 = 197,
	SWF_NAMED_COLOR_PVP_TICKER_STROKE = 198,
	SWF_NAMED_COLOR_PVP_TICKER_BACKER = 199,
	SWF_NAMED_COLOR_PVP_TICKER_SLAYER = 200,
	SWF_NAMED_COLOR_DEMON_RETICLE = 201,
	SWF_NAMED_COLOR_REVENANT_RETICLE_GLOW = 202,
	SWF_NAMED_COLOR_REVENANT_RETICLE_GRADIENT = 203,
	SWF_NAMED_COLOR_REVENANT_RETICLE_BASE = 204,
	SWF_NAMED_COLOR_ARCHVILE_RETICLE_GLOW = 205,
	SWF_NAMED_COLOR_ARCHVILE_RETICLE_GRADIENT = 206,
	SWF_NAMED_COLOR_ARCHVILE_RETICLE_BASE = 207,
	SWF_NAMED_COLOR_PAIN_ELEMENTAL_RETICLE_GLOW = 208,
	SWF_NAMED_COLOR_PAIN_ELEMENTAL_RETICLE_GRADIENT = 209,
	SWF_NAMED_COLOR_PAIN_ELEMENTAL_RETICLE_BASE = 210,
	SWF_NAMED_COLOR_PAIN_ELEMENTAL_RETICLE_WARNING_GRADIENT = 211,
	SWF_NAMED_COLOR_PAIN_ELEMENTAL_RETICLE_WARNING_BASE = 212,
	SWF_NAMED_COLOR_MILESTONE_COMPLETED_BASE = 213,
	SWF_NAMED_COLOR_MILESTONE_COMPLETED_GRADIENT = 214,
	SWF_NAMED_COLOR_MILESTONE_COMPLETED_ICON = 215,
	SWF_NAMED_COLOR_MILESTONE_COMPLETED_TEXT = 216,
	SWF_NAMED_COLOR_PROGRESSION_ITEM_COMPLETED_BASE = 217,
	SWF_NAMED_COLOR_SENTINEL_ARMOR_STROKE = 218,
	SWF_NAMED_COLOR_SENTINEL_ARMOR_GLOW = 219,
	SWF_NAMED_COLOR_SCREEN_DAMAGE = 220,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_FRAG = 221, //! equipment colors will change depending on profile
	SWF_NAMED_COLOR_HUD_EQUIPMENT_FRAG_ICON = 222,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_CYRO = 223,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_CYRO_ICON = 224,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_CHAINSAW = 225,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_CHAINSAW_ICON = 226,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_FLAME_BELCH = 227,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_FLAME_BELCH_ICON = 228,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_CRUCIBLE = 229,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_CRUCIBLE_ICON = 230,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_HAMMER = 231,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_HAMMER_ICON = 232,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_HAMMER_SUPERCHARGE = 233,
	SWF_NAMED_COLOR_HUD_EQUIPMENT_HAMMER_GRADIENT = 234,
	SWF_NAMED_COLOR_HUD_BOSS_HEALTH_BASE = 235, //? changes color with profile
	SWF_NAMED_COLOR_HUD_BOSS_HEALTH_GRADIENT = 236,
	SWF_NAMED_COLOR_HUD_BOSS_SHIELD_BASE = 237,
	SWF_NAMED_COLOR_HUD_BOSS_SHIELD_GLOW = 238,
	SWF_NAMED_COLOR_HUD_KHAN_MAYKR_BAR_BORDER = 239,
	SWF_NAMED_COLOR_HUD_KHAN_MAYKR_BAR_GRADIENT = 240,
	SWF_NAMED_COLOR_HUD_KHAN_MAYKR_BAR_BASE = 241,
	SWF_NAMED_COLOR_HUD_DEMON_LORD_MORTAR_POI_BASE = 242,
	SWF_NAMED_COLOR_HUD_DEMON_LORD_MORTAR_POI_ARROW = 243,
	SWF_NAMED_COLOR_DOOR_LOCK_RED = 244, //! thoses door color keep color in any profile
	SWF_NAMED_COLOR_DOOR_LOCK_BLUE = 245,
	SWF_NAMED_COLOR_DOOR_LOCK_YELLOW = 246,
	SWF_NAMED_COLOR_DOOR_LOCK_GREEN = 247,
	SWF_NAMED_COLOR_INVASION_RED = 248, //? these are overwritten by us, do not use !
	SWF_NAMED_COLOR_INVASION_ORANGE = 249,
	SWF_NAMED_COLOR_INVASION_YELLOW = 250,
	SWF_NAMED_COLOR_PLAYER_BADGE_STREAK_WIN = 251,
	SWF_NAMED_COLOR_PLAYER_BADGE_STREAK_LOSS = 252,
	SWF_NAMED_COLOR_MASTER_LEVEL_LOCKED = 253,
	SWF_NAMED_COLOR_SUPPORT_RUNE_BASE = 254,
	SWF_NAMED_COLOR_SUPPORT_RUNE_GLOW = 255,
	SWF_NAMED_COLOR_SUPPORT_RUNE_STROKE = 256,
	SWF_NAMED_COLOR_SUPPORT_RUNE_SELECTION_BASE = 257,
	SWF_NAMED_COLOR_BLOOD_PUNCH_SUPERCHARGE_BASE = 258,
	SWF_NAMED_COLOR_BLOOD_PUNCH_SUPERCHARGE_GLOW = 259,
	SWF_NAMED_COLOR_CURSED_PROWLER_BASE = 260,
	SWF_NAMED_COLOR_CURSED_PROWLER_GLOW = 261,
	SWF_NAMED_COLOR_POWERUP_ONSLAUGHT = 262,
	SWF_NAMED_COLOR_POWERUP_OVERDRIVE = 263,
	SWF_NAMED_COLOR_POWERUP_BERSERK = 264,
	SWF_NAMED_COLOR_HORDE_PROGRESS_SUCCESS = 265,
	SWF_NAMED_COLOR_HORDE_PROGRESS_CURRENT = 266,
	SWF_NAMED_COLOR_HORDE_PROGRESS_LOCKED = 267,
	SWF_NAMED_COLOR_HORDE_PROGRESS_BONUS = 268,
	SWF_NAMED_COLOR_MAX = 269, //? Watch out we have 2 max colors (receipe for disaster but one max is a custom one.
	SWF_CUSTOM_NAMED_COLOR_DEFAULT = 300,
	SWF_CUSTOM_NAMED_COLOR_RED = 301,
	SWF_CUSTOM_NAMED_COLOR_GREEN = 302,
	SWF_CUSTOM_NAMED_COLOR_BLUE = 303,
	SWF_CUSTOM_NAMED_COLOR_YELLOW = 304,
	SWF_CUSTOM_NAMED_COLOR_MAGENTA = 305,
	SWF_CUSTOM_NAMED_COLOR_CYAN = 306,
	SWF_CUSTOM_NAMED_COLOR_ORANGE = 307,
	SWF_CUSTOM_NAMED_COLOR_PURPLE = 308,
	SWF_CUSTOM_NAMED_COLOR_PINK = 309,
	SWF_CUSTOM_NAMED_COLOR_BROWN = 310,
	SWF_CUSTOM_NAMED_COLOR_WHITE = 311,
	SWF_CUSTOM_NAMED_COLOR_LIGHTGREY = 312,
	SWF_CUSTOM_NAMED_COLOR_MIDGREY = 313,
	SWF_CUSTOM_NAMED_COLOR_DARKGREY = 314,
	SWF_CUSTOM_NAMED_COLOR_BLACK = 315,
	SWF_CUSTOM_NAMED_COLOR_LIGHTBLUE = 316,
	SWF_CUSTOM_NAMED_COLOR_DARKBLUE = 317,
	SWF_CUSTOM_NAMED_COLOR_LIGHTGREEN = 318,
	SWF_CUSTOM_NAMED_COLOR_DARKGREEN = 319,
	SWF_CUSTOM_NAMED_COLOR_LIGHTRED = 320,
	SWF_CUSTOM_NAMED_COLOR_LIGHTYELLOW = 321,
	SWF_CUSTOM_NAMED_COLOR_DARKPURPLE = 322,
	SWF_CUSTOM_NAMED_COLOR_LIGHTPINK = 323,
	SWF_CUSTOM_NAMED_COLOR_DARKBROWN = 324,
	SWF_CUSTOM_NAMED_COLOR_INVISIBLE = 325

};


enum class GameLanguage
{
	Undefined,
	English,
	French,
	German,
	Italian,
	Japanese,
	Polish,
	Portuguese,
	Russian,
	Spanish
};



enum class ExistingModError
{
	NoPreviousModVersionFound,
	GrenadeKeysModAndQolFound,
	GrenadeKeysModAndQolDebugFound,
	GrenadeKeysModAndQol_04Found,
	ExceptionError
};

enum class ModFileToDelete {
	XInput9_1_0,
	DINPUT8
};


enum class idFontHash : uint32_t {
	unknown = 0,
	courier = 0x3918FE2D,
	eternal_bold = 0x506496C8,
	eternal_reg = 0xA6BCB879,
	eternal_num = 0x81ED4377,
	tt_supermolot = 0xC6CE5974,
	idTactical = 0x76E299DB,
	eurostileconreg = 0xFF76BFA6	
};


/*
21:55:33.774       idFontManager.cpp:315   INFO| font: courier hash: 957939245 (hex: 0x3918FE2D enum val: addr: 000001EEACC63160
21:55:33.774       idFontManager.cpp:316   INFO| font: eternal bold hash: 1348769480 (hex: 0x506496C8 enum val: addr: 000001ED9F91CFF0
21:55:33.774       idFontManager.cpp:317   INFO| font: eternal regular hash: -1497581447 (hex: 0xA6BCB879 enum val: addr: 000001ED9F91C440
21:55:33.774       idFontManager.cpp:318   INFO| font: eternal numeral regular hash: -2115157129 (hex: 0x81ED4377 enum val: addr: 000001ED9F91C5A0
21:55:33.774       idFontManager.cpp:319   INFO| font: tt supermolot hash: -959555212 (hex: 0xC6CE5974 enum val: addr: 000001EEACC62DF0
21:55:33.774       idFontManager.cpp:320   INFO| font: idtactical_regular hash: 1994562011 (hex: 0x76E299DB enum val: addr: 000001EEACC61CC0
21:55:33.774       idFontManager.cpp:321   INFO| font: eurostileconreg hash: -8994906 (hex: 0xFF76BFA6 enum val: addr: 000001EEACC62D40
*/

//enum class idFontHash : unsigned int {
//	unknown = 0,		//! works
//	eternal88 = 1,		//! works
//	eternal90 = 2,		//! thin font 
//	ttSuper98 = 3,		//! 7 segments style
//	ttSuperA0 = 4,		//! stylish 
//	idTacticA8 = 5,		//! flatter 
//	euroStilB0 = 6,		//! very thin and low alpha value
//	//eternalB8,		//! no display (for fr at least)
//	/*eternalC0,
//	dfpop3w1C8,
//	dfpop2w9D0,
//	dfpop1w5D8,
//	dfpop3w1E0,
//	koreantkE8,
//	koreansnF0,*/
//	defaultCourrierF8 = 7,
//	MAX_ID_FONTS
//
//};


enum class UI_Scalling {

	Small = 0,
	Medium = 1,
	Large = 2
};

enum class UI_ReticleMode {
	Unknown = -1,
	Full = 0,
	Dot = 1,
	None = 2
};

//! 0:Full  1:Dot  2:None (No Crosshair)
enum gameSettingsCrosshairMode {
	FULL = 0,
	DOT = 1,
	NONE = 2
};

enum class ImmersiveCrosshairLevel {
	IMMERSIVE_CROSSHAIR_LEVEL_UNKNOWN = -1,
	NO_IMMERSIVE_CROSSHAIR = 0,
	HAR_ADS, //! only displayed when ads view of Har
	HAR_ADS_BALISTA_ADS, //! only displayed in har ads and ads view of balista
	HAR_ADS_BALISTA_BOTH,	 //! only displayed in har ads and in both views of balista
	MAX_IMMERSIVE_CROSSHAIR
};


//! a slight variation on idDeclWeaponReticle_reticleStyle_t
enum  class reticleStyle_t {
	RETICLE_K_STYLE_UNKNOWN = -2,
	RETICLE_K_DEFAULT_STYLE = -1, // will use whatever style is defined for the weapon reticle
	RETICLE_STYLE_NONE = 0, // no crosshair on hud
	RETICLE_STYLE_DOT = 1,
	RETICLE_STYLE_ROCKET_LAUNCHER = 2,
	RETICLE_STYLE_SHOTGUN = 3,
	RETICLE_STYLE_SHOTGUN_STICKY_BOMBS = 4,
	RETICLE_STYLE_SHOTGUN_STICKY_BOMBS_MASTERY = 5,
	RETICLE_STYLE_SHOTGUN_FULL_AUTO = 6,
	RETICLE_STYLE_HEAVY_CANNON = 7,
	RETICLE_STYLE_HEAVY_CANNON_BOLT = 8,
	RETICLE_STYLE_DB_SHOTGUN = 9,
	RETICLE_STYLE_DB_SHOTGUN_MEATHOOK = 10,
	RETICLE_STYLE_PLASMA = 11,
	RETICLE_STYLE_PLASMA_MICROWAVE = 12,
	RETICLE_STYLE_PLASMA_AOE = 13,
	RETICLE_STYLE_PLASMA_STUN_FASTER_RECHARGE = 14,
	RETICLE_STYLE_CHAINGUN = 15,
	RETICLE_STYLE_CHAINGUN_TURRET = 16,
	RETICLE_STYLE_CHAINGUN_TURRET_NOHEAT = 17,
	RETICLE_STYLE_BALLISTA_ARBALEST = 18, //? this is arbalest hips AND ads view unfortunately 
	RETICLE_STYLE_BALLISTA_DESTROYER = 19,
	RETICLE_STYLE_BALLISTA_DESTROYER_MASTERY = 20,
	RETICLE_STYLE_CHAINSAW = 21,
	RETICLE_STYLE_ROCKET_LAUNCHER_LOCKON = 22,
	RETICLE_STYLE_BFG = 23,
	RETICLE_STYLE_CRUCIBLE = 24,
	RETICLE_STYLE_UNMAKYR = 25,
	RETICLE_STYLE_PISTOL = 26,
	RETICLE_STYLE_MP_BARON = 27,
	RETICLE_STYLE_MP_REVENANT = 28,
	RETICLE_STYLE_MP_PROWLER = 29,
	RETICLE_STYLE_MP_MANCUBUS = 30,
	RETICLE_STYLE_MP_HARVESTER = 31,
	RETICLE_STYLE_MP_CACODEMON = 32,
	RETICLE_STYLE_MP_PINKY = 33,
	RETICLE_STYLE_MP_ARCHVILE = 34,
	RETICLE_STYLE_MP_MARAUDER = 35,
	RETICLE_STYLE_MP_DREADKNIGHT = 36,
	RETICLE_STYLE_MAX = 37,
};


enum class HitMarkerState {
	ON = 0,
	OFF = 1
};

enum eventType_t : int32_t {
	EVENT_GAME = 0,
	EVENT_ACTION = 1,
	EVENT_ANIMEVENT = 2,
	EVENT_FSMEVENT = 3,
	EVENT_NOTICE = 4,
	EVENT_SSACTION = 5
};