#pragma once
#include <windows.h>
#include <string>
#include <cstdio> // Include the C Standard I/O header

#include "IniFileData.h"
//#include "Config.h"
#include "../Config/Config.h"
#include "Common.h"



class iniStr {

private:

	static std::string m_baseStr;
	static std::string m_namedIdsColorsStr;
	static std::string m_iniFileColorIdsStr;
		

public:

	static std::string getIniWholeStr() {
		return getBaseStr();
	}

	//? Reminder you have to put a # in front of the string that is going to just be a string
	static std::string& getBaseStr() {
		char buffer[16384]; // Adjust the buffer size as needed
		sprintf(buffer,
			"\n"
			"\n"
			"\n"
			"[Info]\n"
			"IniFileVersion = %s; \n"
			"\n"
			"# Dedicated Grenades Keys Mod Ini File Settings \n"			
			"# Mod Author: %s \n"
			"\n"
			"# These are the user settings. You don't have to change anything in this file for the mod to work. For more info check the install.txt file. \n"
			"\n"
			"# If you want, for example, to change the sensitivity of the precision bold while the game is running, you have to edit this file and SAVE IT (and then press the ReloadFileKey while in game if you haven't enabled iniFile auto reload)\n"
			"\n"
			"# ONLY MODIFY THE USER FIELDS OF THIS FILE OR IT COULD MESS THE PARSING SYSTEM. IF YOU HAVE ISSUES WITH THIS FILE or want to reset it to its original values you can, close the the .ini file, close the game, delete the .ini file, and relaunch the game, that way the .ini file gets regenerated automatically.\n"
			"\n"
			"\n"
			"#####################   !!!!! IDs OF COLORS AT THE BOTTOM OF THIS FILE !!!!!   #####################"
			"\n"
			"\n"
			"[Settings]\n"
			"\n"
			"\n"
			"Auto_Reload_Ini_File = %s ;    (A new experimental feature, if set to yes, when you make changes to this file AND SAVE IT, when you alt tab back to the game and are playing in a level, the mod will automatically refresh the changes in this file without having to press the ReloadFile Key. I you have any issue with this feature though, set it to no, or if it's stuck on a loop of 'ini file reloaded voice' quit the game, and delete the ini file. HOWEVER KEEP IN MIND THE FIRST TIME YOU ENABLE THIS YOU WILL HAVE TO PRESS THE RELOAD FILE KEY ONCE YOU ATL TAB BACK IN THE GAME yes: enable auto reload. no: disables auto reload.) \n"
			"\n"
			"\n"
			"Reload_Ini_File_Key = %s ;    (If you haven't enabled auto reload feature above, this is the key you press once in the game after you have mades changes to this file. Possible keys: A-Z or 0-9 or F1-12, but other keys or modifiers will not work and will default back to F8. once again if you haven't enabled auto reload, YOU HAVE TO PRESS THIS KEY ONCE YOU ALT TAB INTO BACK IN THE GAME FOR THE SETTINGS TO UPDATE AND YOU WILL HEAR A VOICE TELLING YOU IF THE FILE WAS CORRECTLY SAVED AND PARSED) \n"
			"\n"
			"\n"			
			"Crosshair_Scale = %d ;    (from 0 to 200. Will scale the values of all crosshairs, even the dot (But will not modify the bolt action ADS one cause of hud scalling issues.) The lower the value the smaller the crosshair. Default Game value: 100)\n"			
			"\n"
			"\n"
			"Immersive_Crosshair_Level = %d ;    (This is for people who like to play with no crosshair BUT who think that there should be one in some ADS weapons. 1 :will only show crosshair for HAR ADS. 2 :only show crosshair for HAR and Balista ADS. 3 :only show crosshair for HAR and Balista when it's in ADS or not.  0 :normal crosshairs behaviour. IN THIS MODE THE SIZE OF THE CROSSHAIRS IS DEFAULT.)\n"
			"\n"
			"\n"
			"Dot_Crosshair_Color = %d ;    (the color id of the dot crosshair. White by default but you can set it to anything you want. default color id: %d\n"
			"\n"			
			"\n"
			"Dot_Crosshair_Cooldown_Color = %d ;    (the color id of the dot crosshair when the weapon is on cooldown for example if the meathook is recharging, or the shotgun stickies are recharging. If you don't want this feature, set this value to 300. default color index: %d\n"
			"\n"
			"\n"
			"Dot_Crosshair_Frag_Nade_Ready_Color = %d ;    (the color id of the dot crosshair when frag grenade is ready. If you don't want to use this feature just set this value to %d. Default color index: %d \n"
			"\n"
			"\n"
			"Dot_Crosshair_Ice_Nade_Ready_Color = %d ;    (the color id of the dot crosshair when ice grenade is ready. If you don't want to use this feature just set this value to %d. Default color index: %d \n"
			"\n"
			"\n"
			"Dot_Crosshair_Both_Nades_Ready_Color = %d ;    (the color id of the dot crosshair when both grenades, frag and ice are ready. If you don't want to use this feature just set this value to %d. Default color index: %d \n"
			"\n"
			"\n"
			"BloodPunch_1_Icon_Color = %d ;    (the color id of the Bloodpunch icon if you have 1 bloodpunch ready. It's a great visual feedback give it a try. If you want the original game color set this to 300. default color index: %d If you have no bloodpunch the icon will be the default hud color \n"
			"\n"
			"\n"
			"BloodPunch_2_Icon_Color = %d ;    (the color id of the Bloodpunch icon if you have 2 bloodpunches ready. If you want the original game color set this to 300. default color index: %d \n"
			"\n"
			"\n"
			"Desperate_Punch_Icon_Color = %d ;    (the color id of the Desperate Bloodpunch icon when the desperate punch is ready (only available in dlc). If you want the original game color set this to 300. default color index: %d \n"
			"\n"
			"\n"
			"Fuel_3_Pips_Icon_Color = %d ;    ( the color of the fuel icon when you have 3 fuels available, so you get a color feedback that you can chainsaw a heavy. If you want the original game color set this to 300. default color index: %d \n"
			"\n"
			"\n"
			"FragNade_Ready_Icon_Color = %d ;    ( the color of the frag grenade icon. For example you may want to change this to make it more green to make it easier to see/notice. If you want the original game color set this to 300. default color index: %d \n"
			"\n"
			"\n"
			"FragNade_Cooldown_Icon_Color = %d ;    (the color id of the frag nade icon when it is recharging. If you want the original game color set this to 300.  Default color index: %d \n"
			"\n"
			"\n"
			"IceNade_Ready_Icon_Color = %d ;    (the color id of the custom ice nade icon when the ice grenade is ready. If you want the original game color set it to 300. default color index: %d \n"
			"\n"
			"\n"
			"IceNade_Cooldown_Icon_Color = %d ;    (the color id of the ice nade icon when the ice grenade is recharging. If you want the original game color set this to 300.  Default color index: %d \n"
			"\n"
			"\n"
			"Colored_Weapon_Bar = %s ;    (no: will make the weapon/ammo info on the hud white instead of being weapon colored like red for rockets or purple for plasma, the goal is to reduce the color feedback so the grenades and equipments colors are easier or more intuitive to notice. yes: default game setting)\n"
			"\n"
			"\n"
			"Radsuit_Bar_Color = %d ;    (The color id of the radsuit bar so that it's easily distinguishable from the armor bar meter color. If you want the original game color set this to 300. default color index: %d \n"
			"\n"
			"\n"
			"Clean_Hud = %s ;    (yes: will remove the binds reminders on the hud, if you've played the game a bit you don't need those anymore, and it does makes the hud look so much better this way. no: default game setting)\n"
			"\n"
			"\n"
			"Disable_Hit_Marker = %s ;    (yes: will remove the little X that shows up when you hit a target. no: default game setting)\n"
			"\n"
			"\n"
			"Remove_Dash_Blur_Effect = %s ;    (yes: will remove the white border effect everytime you dash, this can help if you feel a bit nauseous/headache when playing for a long time. no: default game setting. IF YOU DISABLED IT AND WANT TO RE-ENABLE IT, SET IT TO NO, SAVE AND RESTART THE GAME)\n"
			"\n"
			"\n"
			"Game_Settings_Min_FOV = %d ;    (from 70 to 90. The min FOV you can set in the game options screen. default: 90)\n"
			"\n"
			"\n"
			"Game_Settings_Max_FOV = %d ;    (from 120 to 150. The max FOV you can set in the game options screen. default: 120)\n"
			"\n"
			"\n"
			"Weapon_FOV_Override = %d ;    (from 0 to 100. This controls how much you see the weapon model. If you set this very low you can even make the weapon disappear while keeping the same view FOV. Higer values means you'll see more of the weapon. default game setting: 0)\n"
			"\n"
			"\n"
			"PrecisionBolt_ADS_Mouse_Sens  = %d ;    (from 0 to 100. The lower, the slower mouse mouvements, default game setting: 50) \n"
			"\n"
			"\n"
			"Arbalest_ADS_Mouse_Sens = %d ;    (from 0 to 100. The lower, the slower mouse mouvements, default game setting: 60) \n"
			"\n"
			"\n"
			"PrecisionBolt_ADS_Controller_Sens  = %d ;    (from 0 to 100, the lower the slower the controller mouvements, default game setting: 40)\n"
			"\n"
			"\n"
			"Arbalest_ADS_Controller_Sens = %d ;    (from 0 to 100, the lower the slower the controller mouvements, default game setting: 60)\n"
			"\n"
			"\n"
			"Remove_Shotguns_Zoom_And_Sens_Change  = %s ;    (yes: removes the zoom effects and forced lowered sensitivity when using sticky bombs and full auto mods. no: uses default game behaviour)\n"
			"\n"
			"\n"
			"Remove_Balista_Arbalest_Zoom  = %s ;    (yes: removes the zoom effect when using Balista Arbalest. no: uses default game behaviour)\n"
			"\n"
			"\n"
			"Weapon_Switch_Fix  =  %s ;    (An experimental feature that attempts to improve the reliability of weapon switching for mouse and keyboard users. If you have the feeling that sometimes in heated situation that the weapon you're holding doesn't corresond to the key you pressed, turn this feature on. yes: enables weapon switch fix. no: uses default game behaviour)\n"
			"\n"
			"\n"
			"Weapon_Switch_Fix_Beep = %s ;    (yes: plays a small beep when the mod detects a weapon switch error and resends the right weapon button/key, this is more of a debug feature. no: no beep.)\n"
			"\n"
			"\n"			
			"Mod_Loaded_Beep  = %s ;    (yes: plays 2 beeps when the mod load succesfully. no: does not play any beep when mod is loaded.\n"			
			"\n"
			"\n"
			"Debug_Level = %d ;    (Requires Game Restart. Only change this if you know what you are doing as this could affect performance. This is more like a troubleshooting tool. 0: default value, limited logs, 1: more logs, 2: even more logs"
				"\n""\n""\n""%s", IniFileData::getIniFileVersionAsStr().c_str(), g_modAuthor.c_str(), IniFileData::getIsInifileAutoReloadStr().c_str(), IniFileData::getreloadIniFileVkCodeStr().c_str(), IniFileData::getReticleScaleInt(), IniFileData::getImmersiveCrosshairLevelInt(), IniFileData::getOverrideReticleColorInt(), IniDefault::g_defaultOverrideDotReticleColor, IniFileData::getOverrideReticleCooldownColorInt(), IniDefault::g_defaultOverrideDotReticleCooldownColor, IniFileData::getOverrideDotReticleFragNadeReadyColorInt(), IniDefault::g_DotColorFeatureDisabledColor, IniDefault::g_defaultOverrideDotReticleFragNadeReadyColor, IniFileData::getOverrideDotReticleIceNadeReadyColorInt(), IniDefault::g_DotColorFeatureDisabledColor, IniDefault::g_defaultOverrideDotReticleIceNadeReadyColor, IniFileData::getOverrideDotReticleBothNadeReadyColorInt(), IniDefault::g_DotColorFeatureDisabledColor, IniDefault::g_defaultOverrideDotReticleBothNadesReadyColor, IniFileData::getOverrideBloodPunchColor1Int(), IniDefault::g_defaultOverrideBloodPunchColor1, IniFileData::getOverrideBloodPunchColor2Int(), IniDefault::g_defaultOverrideBloodPunchColor2, IniFileData::getOverrideDesperatePunchInt(), IniDefault::g_defaultOverrideDesperatePunchColor, IniFileData::getOverrideFuel3PipsColorInt(), IniDefault::g_defaultOverrideFuel3Pips_Color, IniFileData::getOverrideFragGrenadeColorInt(), IniDefault::g_defaultOverrideFragGrenadeAvailable_Color, IniFileData::getOverrideFragGrenadeCoolDownColorInt(), IniDefault::g_defaultOverrideFragGrenadeCooldown_Color, IniFileData::getOverrideIceGrenadeColorInt(), IniDefault::g_defaultOverrideIceGrenadeAvailable_Color, IniFileData::getOverrideIceGrenadeCooldownColorInt(), IniDefault::g_defaultOverrideIceGrenadeCoolDown_Color, IniFileData::getIsIsWeaponBarColoredStr().c_str(), IniFileData::getOverrideRadMeterColorInt(), IniDefault::g_defaultOverrideRadMeterColor, IniFileData::getIsRemoveBindsReminderOnHudStr().c_str(), IniFileData::getIsDisableHitMarkerStr().c_str(), IniFileData::getIsDisableDashBlurEffectStr().c_str(), IniFileData::getGameUiSettingsMinFovInt(), IniFileData::getGameUiSettingsMaxFovInt(), IniFileData::getHandsFovInt(), IniFileData::getassaultRiflePrecisionBoltMouseSensInt(), IniFileData::getballistaArbalestMouseSensInt(), IniFileData::getssaultRiflePrecisionBoltControllerSensInt(), IniFileData::getballistaArbalestControllerSensInt(), IniFileData::getisOverideShotgunConfigStr().c_str(), IniFileData::getIsRemoveBalistaZoomStr().c_str(), IniFileData::getisImprovedWeaponSwitchingStr().c_str(), IniFileData::getisImprovedWeaponSwitchingBeepStr().c_str(), IniFileData::getisPlayModLoadedBeepStr().c_str(), IniFileData::getIsUserDebugModLevelInt(), m_iniFileColorIdsStr.c_str());

		m_baseStr = buffer;
		return m_baseStr;
	}

	static std::string getnamedIdsColorsStr() {
		//! those are direct values from swfNamedColors_t but some values have been skipped
		return m_namedIdsColorsStr;			
	}

};

 std::string iniStr::m_baseStr = "Error: ini string uninitialized. Contact the mod author on nexus forum";

 std::string iniStr::m_iniFileColorIdsStr =
	 "# # COLOR IDs : Use those numbers to set the color you want the huds elements, for example if you want the Ice Grenade arrow icon to become Purple, IceNade_Ready_Arrow_Color = 316 should become  IceNade_Ready_Arrow_Color = 308\n"
	 "\n"
	 "#\tDefault: 300\n"
	 "#\tRed: 301\n"
	 "#\tGreen: 302\n"
	 "#\tBlue: 303\n"
	 "#\tYellow: 304\n"
	 "#\tMagenta: 305\n"
	 "#\tCyan: 306\n"
	 "#\tOrange: 307\n"
	 "#\tPurple: 308\n"
	 "#\tPink: 309\n"
	 "#\tBrown: 310\n"
	 "#\tWhite: 311\n"
	 "#\tLightGrey: 312\n"
	 "#\tMidGrey: 313\n"
	 "#\tDarkGrey: 314\n"
	 "#\tBlack: 315\n"
	 "#\tLightBlue: 316\n"
	 "#\tDarkBlue: 317\n"
	 "#\tLightGreen: 318\n"
	 "#\tDarkGreen: 319\n"
	 "#\tLightRed: 320\n"
	 "#\tLightYellow: 321\n"
	 "#\tDarkPurple: 322\n"
	 "#\tLightPink: 323\n"
	 "#\tDarkBrown: 324\n";  



 //? not using this as i managed to create my own colors:
 std::string iniStr::m_namedIdsColorsStr = "# # COLOR IDs : \n"
	 "# \t COLOR_HUD_BASE = 0,\n"
	 "# \t COLOR_HUD_SHADOW = 1, \n"
	 "# \t COLOR_HUD_TEXT = 2,  \n"
	 "# \t COLOR_HUD_HEADER = 3,\n"
	 "# \t COLOR_DASH_BASE = 4,\n"
	 "# \t COLOR_DASH_GLOW = 5,\n"
	 "# \t COLOR_NOTIFICATION_GHOST = 6,\n"
	 "# \t COLOR_UI_HEALTH = 7,\n"
	 "# \t COLOR_UI_HEALTH_GRADIENT = 8,\n"
	 "# \t COLOR_UI_HEALTH_LOW = 9,\n"
	 "# \t COLOR_UI_HEALTH_REALLY_LOW = 10,\n"
	 "# \t COLOR_UI_HEALTH_DEMON = 11,\n"
	 "# \t COLOR_UI_ARMOR = 12,\n"
	 "# \t COLOR_UI_ARMOR_GRADIENT = 13,\n"
	 "# \t COLOR_UI_RADIATION = 14,\n"
	 "# \t COLOR_UI_RADIATION_GRADIENT = 15,\n"
	 "# \t COLOR_UI_OXYGEN = 16,\n"
	 "# \t COLOR_UI_OXYGEN_GRADIENT = 17,\n"
	 "# \t COLOR_UI_WARNING = 18,\n"
	 "# \t COLOR_UI_CAUTION = 19,\n"
	 "# \t COLOR_UI_SUCCESS = 20,\n"
	 "# \t COLOR_UI_FAILURE = 21,\n"
	 "# \t COLOR_UI_DEMON_HEALTH_PIP_GREEN = 31,\n"
	 "# \t COLOR_UI_DEMON_HEALTH_PIP_GREEN_GRADIENT = 32,\n"
	 "# \t COLOR_UI_DEMON_HEALTH_PIP_ORANGE = 33, \n"
	 "# \t COLOR_UI_DEMON_HEALTH_PIP_ORANGE_GRADIENT = 34,\n"
	 "# \t COLOR_UI_DEMON_HEALTH_PIP_BLUE = 35,\n"
	 "# \t COLOR_UI_DEMON_HEALTH_PIP_BLUE_GRADIENT = 36,\n"
	 "# \t COLOR_UI_DEMON_HEALTH_PIP_LOW = 37,\n"
	 "# \t COLOR_UI_DEMON_HEALTH_PIP_LOW_GRADIENT = 38,\n"
	 "# \t COLOR_UI_DEMON_HEALTH_PIP_DEAD = 39,\n"
	 "# \t COLOR_WORLD_UNLOCKED = 52,\n"
	 "# \t COLOR_WORLD_LOCKED = 53,\n"
	 "# \t COLOR_SLAYER_GREEN = 54, \n"
	 "# \t COLOR_DEMON_RED = 55,\n"
	 "# \t COLOR_DEMON_YELLOW = 56, \n"
	 "# \t COLOR_WHITE = 57, \n"
	 "# \t COLOR_WEAPON_CHAINSAW = 58, \n"
	 "# \t COLOR_WEAPON_SHOTGUN = 59,\n"
	 "# \t COLOR_WEAPON_DOUBLE_BARREL = 60,\n"
	 "# \t COLOR_WEAPON_ASSUALT_RIFLE = 61,\n"
	 "# \t COLOR_WEAPON_CHAINGUN = 62,\n"
	 "# \t COLOR_WEAPON_PLASMA_RIFLE = 63,\n"
	 "# \t COLOR_WEAPON_BALLISTA = 64,\n"
	 "# \t COLOR_WEAPON_ROCKET_LAUNCHER = 65,\n"
	 "# \t COLOR_WEAPON_BFG = 66,\n"
	 "# \t COLOR_WEAPON_UNMAYKR = 67,\n"
	 "# \t COLOR_WEAPON_CRUCIBLE = 68,\n"
	 "# \t COLOR_WEAPON_HAMMER = 69,\n"
	 "# \t COLOR_WEAPON_NO_AMMO = 70,\n"
	 "# \t COLOR_WEAPON_DISABLED = 71,\n"
	 "# \t COLOR_WEAPON_SHOTGUN_FULL = 72,\n"
	 "# \t COLOR_WEAPON_DOUBLE_BARREL_FULL = 73,\n"
	 "# \t COLOR_WEAPON_ASSUALT_RIFLE_FULL = 74,\n"
	 "# \t COLOR_WEAPON_CHAINGUN_FULL = 75,\n"
	 "# \t COLOR_WEAPON_PLASMA_RIFLE_FULL = 76,\n"
	 "# \t COLOR_WEAPON_BALLISTA_FULL = 77,\n"
	 "# \t COLOR_WEAPON_ROCKET_LAUNCHER_FULL = 78,\n"
	 "# \t COLOR_WEAPON_BFG_FULL = 79,\n"
	 "# \t COLOR_WEAPON_UNMAYKR_FULL = 80,\n"
	 "# \t COLOR_WEAPON_HAMMER_FULL = 81,\n"
	 "# \t COLOR_RETICLE_BASE = 82,\n"
	 "# \t COLOR_RETICLE_GLOW = 83,\n"
	 "# \t COLOR_RETICLE_COOLDOWN_BASE = 84,\n"
	 "# \t COLOR_RETICLE_COOLDOWN_GLOW = 85,\n"
	 "# \t COLOR_RETICLE_WARNING_BASE = 86,\n"
	 "# \t COLOR_RETICLE_WARNING_GLOW = 87,\n"
	 "# \t COLOR_KEYCARD_BLUE = 94,\n"
	 "# \t COLOR_KEYCARD_RED = 95,\n"
	 "# \t COLOR_KEYCARD_YELLOW = 96,\n"
	 "# \t COLOR_KEYCARD_SLAYER = 97,\n"
	 "# \t COLOR_COLLECTED_ITEM = 104,\n"
	 "# \t COLOR_CORRUPTION_HEX_CLEARED = 105,\n"
	 "# \t COLOR_CORRUPTION_HEX_GLOW_CLEARED = 106,\n"
	 "# \t COLOR_CORRUPTION_HEX_CORRUPT = 107,\n"
	 "# \t COLOR_CORRUPTION_HEX_GLOW_CORRUPT = 108,\n"
	 "# \t COLOR_CORRUPTION_CONTAINER_CLEARED = 109,\n"
	 "# \t COLOR_CORRUPTION_CONTAINER_CORRUPT = 110,\n"
	 "# \t COLOR_CORRUPTION_CLEARED = 111,\n"
	 "# \t COLOR_CORRUPTION_CLEARED_GLOW = 112,\n"
	 "# \t COLOR_CORRUPTION_PARTIAL_CLEARED = 113,\n"
	 "# \t COLOR_CORRUPTION_PARTIAL_CLEARED_GLOW = 114,\n"
	 "# \t COLOR_CORRUPTION_COMBAT = 115,\n"
	 "# \t COLOR_CORRUPTION_COMBAT_GLOW = 116,\n"
	 "# \t COLOR_CORRUPTION_SLAYER_GATE = 117,\n"
	 "# \t COLOR_CORRUPTION_SLAYER_GATE_GLOW = 118,\n"
	 "# \t COLOR_CORRUPTION_SECRET = 119,\n"
	 "# \t COLOR_CORRUPTION_SECRET_GLOW = 120,\n"
	 "# \t COLOR_DEMON_HUD_YELLOW_BASE = 145,\n"
	 "# \t COLOR_DEMON_HUD_YELLOW_GRADIENT = 146,\n"
	 "# \t COLOR_DEMON_HUD_YELLOW_OVERLAY = 147,\n"
	 "# \t COLOR_DEMON_HUD_YELLOW_ICON = 148,\n"
	 "# \t COLOR_DEMON_HUD_ORANGE_BASE = 149,\n"
	 "# \t COLOR_DEMON_HUD_ORANGE_GRADIENT = 150,\n"
	 "# \t COLOR_DEMON_HUD_ORANGE_OVERLAY = 151,\n"
	 "# \t COLOR_DEMON_HUD_ORANGE_ICON = 152,\n"
	 "# \t COLOR_DEMON_HUD_BLUE_BASE = 153,\n"
	 "# \t COLOR_DEMON_HUD_BLUE_GRADIENT = 154,\n"
	 "# \t COLOR_DEMON_HUD_BLUE_OVERLAY = 155,\n"
	 "# \t COLOR_DEMON_HUD_BLUE_ICON = 156,\n"
	 "# \t COLOR_DEMON_HUD_PURPLE_BASE = 157,\n"
	 "# \t COLOR_DEMON_HUD_PURPLE_GRADIENT = 158,\n"
	 "# \t COLOR_DEMON_HUD_PURPLE_OVERLAY = 159,\n"
	 "# \t COLOR_DEMON_HUD_PURPLE_ICON = 160,\n"
	 "# \t COLOR_DEMON_HUD_RED_BASE = 161,\n"
	 "# \t COLOR_DEMON_HUD_RED_GRADIENT = 162,\n"
	 "# \t COLOR_DEMON_HUD_RED_OVERLAY = 163,\n"
	 "# \t COLOR_DEMON_HUD_RED_ICON = 164,\n"
	 "# \t COLOR_DEMON_HUD_GREEN_BASE = 165,\n"
	 "# \t COLOR_DEMON_HUD_GREEN_GRADIENT = 166,\n"
	 "# \t COLOR_DEMON_HUD_GREEN_OVERLAY = 167,\n"
	 "# \t COLOR_DEMON_HUD_GREEN_ICON = 168,\n"
	 "# \t COLOR_DEMON_HUD_ICON_COOLDOWN = 169,\n"
	 "# \t COLOR_DEMON_HUD_BASE_COOLDOWN = 170,\n"
	 "# \t COLOR_SENTINEL_ARMOR_STROKE = 218,\n"
	 "# \t COLOR_SENTINEL_ARMOR_GLOW = 219,\n"
	 "# \t COLOR_SCREEN_DAMAGE = 220,\n"
	 "# \t COLOR_HUD_EQUIPMENT_FRAG = 221,\n"
	 "# \t COLOR_HUD_EQUIPMENT_FRAG_ICON = 222,\n"
	 "# \t COLOR_HUD_EQUIPMENT_CYRO = 223,\n"
	 "# \t COLOR_HUD_EQUIPMENT_CYRO_ICON = 224,\n"
	 "# \t COLOR_HUD_EQUIPMENT_CHAINSAW = 225,\n"
	 "# \t COLOR_HUD_EQUIPMENT_CHAINSAW_ICON = 226,\n"
	 "# \t COLOR_HUD_EQUIPMENT_FLAME_BELCH = 227,\n"
	 "# \t COLOR_HUD_EQUIPMENT_FLAME_BELCH_ICON = 228,\n"
	 "# \t COLOR_HUD_EQUIPMENT_CRUCIBLE = 229,\n"
	 "# \t COLOR_HUD_EQUIPMENT_CRUCIBLE_ICON = 230,\n"
	 "# \t COLOR_HUD_EQUIPMENT_HAMMER = 231,\n"
	 "# \t COLOR_HUD_EQUIPMENT_HAMMER_ICON = 232,\n"
	 "# \t COLOR_HUD_EQUIPMENT_HAMMER_SUPERCHARGE = 233,\n"
	 "# \t COLOR_HUD_EQUIPMENT_HAMMER_GRADIENT = 234,\n"
	 "# \t COLOR_HUD_BOSS_HEALTH_BASE = 235, \n"
	 "# \t COLOR_HUD_BOSS_HEALTH_GRADIENT = 236,\n"
	 "# \t COLOR_HUD_BOSS_SHIELD_BASE = 237,\n"
	 "# \t COLOR_HUD_BOSS_SHIELD_GLOW = 238,\n"
	 "# \t COLOR_HUD_KHAN_MAYKR_BAR_BORDER = 239,\n"
	 "# \t COLOR_HUD_KHAN_MAYKR_BAR_GRADIENT = 240,\n"
	 "# \t COLOR_HUD_KHAN_MAYKR_BAR_BASE = 241,\n"
	 "# \t COLOR_HUD_DEMON_LORD_MORTAR_POI_BASE = 242,\n"
	 "# \t COLOR_HUD_DEMON_LORD_MORTAR_POI_ARROW = 243,\n"
	 "# \t COLOR_DOOR_LOCK_RED = 244, \n"
	 "# \t COLOR_DOOR_LOCK_BLUE = 245,\n"
	 "# \t COLOR_DOOR_LOCK_YELLOW = 246,\n"
	 "# \t COLOR_DOOR_LOCK_GREEN = 247,\n"
	 "# \t COLOR_PLAYER_BADGE_STREAK_WIN = 251,\n"
	 "# \t COLOR_PLAYER_BADGE_STREAK_LOSS = 252,\n"
	 "# \t COLOR_SUPPORT_RUNE_SELECTION_BASE = 257,\n"
	 "# \t COLOR_BLOOD_PUNCH_SUPERCHARGE_BASE = 258,\n"
	 "# \t COLOR_BLOOD_PUNCH_SUPERCHARGE_GLOW = 259,\n"
	 "# \t COLOR_CURSED_PROWLER_BASE = 260,\n"
	 "# \t COLOR_CURSED_PROWLER_GLOW = 261,\n"
	 "# \t COLOR_POWERUP_ONSLAUGHT = 262,\n"
	 "# \t COLOR_POWERUP_OVERDRIVE = 263,\n"
	 "# \t COLOR_POWERUP_BERSERK = 264,\n"
	 "# \t COLOR_HORDE_PROGRESS_SUCCESS = 265,\n"
	 "# \t COLOR_HORDE_PROGRESS_CURRENT = 266,\n"
	 "# \t COLOR_HORDE_PROGRESS_LOCKED = 267,\n"
	 "# \t COLOR_HORDE_PROGRESS_BONUS = 268,\n";

	
//? this is the FragArrowColor color settings, i decided to not use this for the moment and just have the frag permanently selected. If users complain we could reenable it easily but i still need to reduce the complexity of this mod or i'll never finish.
//"FragArrowColor = %d ;    (the color index of the arrow on the right side of the grenade icon when the Frag grenade is ready to be thrown, otherwise it will be invisible.  : default: %d INDEX OF COLORS IS THE BOTTOM OF THIS FILE.)\n""\n""\n"

	

	







